openapi: "3.0.0"
info:
  title: "Book Wishlist API"
  version: "0.1.0"
  description: "Book Wishlist API with Node.js and Express.js"
servers:
  - url: "http://localhost:5003"

tags:
  - name: Users
    description: User Details


# User

paths:
  /register:
    post:
      tags:
        - Login and Registration
      summary: Register a new user.
      description: Endpoint for creating a new user account.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/users'       
      responses:
        '201':
          description: Successfully registered a new user.
        '400':
          description: Bad request. Check the request payload.
        '409':
          description: Conflict. User already exists with the given email or username.
        '500':
          description: Internal server error.
         
  /login:
    post:
      tags:
        - Login and Registration
      summary: Login the current user.
      description: Endpoint for the user to login.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/users'       
      responses:
        '200':
          description: Login successful. Token provided.
        '400':
          description: Bad request. Check the request payload.
        '401':
          description: Invalid Credentials.
        '500':
          description: Internal server error.
         
  /current:
    get:
      tags:
        - Login and Registration
      summary: Details of the current user.
      description: Endpoint for the current user details.
      responses:
        '200':
          description: request successful. Details provided.
        '500':
          description: Internal server error.


# Wishlist

  /:
    get:
      tags:
        - Wishlist
      summary: All books in the user's wishlist.
      description: Endpoint for the current user's wishlist.
      responses:
        '200':
          description: Request successful. Details provided.
        '500':
          description: Internal server error.

    post:
      tags:
        - Wishlist
      summary: To add books in the user's wishlist.
      description: Endpoint for adding book to the current user's wishlist.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/wishlist'       
      responses:
        '201':
          description: Request successful. Details provided.
        '400':
          description: Bad request. Check Payload.
        '500':
          description: Internal server error.
          

  /{id}:
    get:
      tags:
        - Wishlist
      summary: To find the particular book from the current user's wishlist.
      description: Endpoint for finding book from the current user's wishlist.
      parameters:
        - name: id
          in: path
          description: ID of book to return
          required: true
          schema: 
            type: string
      responses:
        '200':
          description: Request successful. Details provided.
        '403':
          description: User is not authenticated to view this content.
        '404':
          description: No such book found in the wishlist.
        '500':
          description: Internal server error.
    
    put:
      tags:
        - Wishlist
      summary: To update the particular book from the current user's wishlist.
      description: Endpoint for updating a book from the current user's wishlist.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/wishlist'       
      parameters:
        - name: id
          in: path
          description: ID of book to return
          required: true
          schema: 
            type: string
      responses:
        '200':
          description: Request successful. Details provided.
        '403':
          description: User is not authenticated to view this content.
        '404':
          description: No such book found in the wishlist.
        '500':
          description: Internal server error.
    
    delete:
      tags:
        - Wishlist
      summary: To delete the particular book from the current user's wishlist.
      description: Endpoint for deleting the book from the current user's wishlist.
      responses:
        '200':
          description: Request successful. Details provided.
        '403':
          description: User is not authenticated to view this content.
        '404':
          description: No such book found in the wishlist.
        '500':
          description: Internal server error.
    

components:
  schemas:
    users:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
        preferredGenre:
          type: string
          items: 
            type: enum

      required:
        - username
        - email
        - password
        - preferredGenre

      example:
        username: abc
        email: user@gmail.com
        password: pass123
        preferredGenre: ['Fiction', 'Non-Fiction', 'Comic', 'Horror']


    wishlist:
      type: object
      properties:
        user_id:
          type: mongoose.Schema.Types.ObjectId
        bookTitle:
          type: string
        bookDescription:
          type: string
        genre:
          type: string
        completionStatus:
          type: string
            items: 
              type: enum

      required:
        - user_id
        - bookTitle
        - bookDescription
        - genre
        - completionStatus

      example:
        user_id: 12343465
        bookTitle: Sherlock Holmes
        bookDescription: Sherlock Holmes is a fictional detective created by British author Arthur Conan Doyle.
        genre: Fiction
        completionStatus: ['Pending', 'Completed']

